NumPy - Numerical Python

Advantages of Numpy Arrays:
  1. Allow Several Mathematical Operations
  2. Faster Operations

In [4]:
import numpy as np

List vs Numpy - Time Taken

In [5]:
from time import process_time

Time Taken by a List

In [6]:
python_list = [i for i in range(100000000)]
start_time = process_time()
python_list = [i + 5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

5.399697238


Time Taken by NumPy Array

In [7]:
np_array = np.array([i for i in range(100000000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.07908307600000342


NumPy Arrays

In [8]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array1 = np.array([1,2,3,4,5])
print(np_array1)
type(np_array1)

[1 2 3 4 5]


numpy.ndarray

Mathematical operation on a np Array

In [14]:
# in Python list
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # Concatenate or joins 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [18]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(11,20,(3,3))
print(a)
print(b)
print(a + b)
print(a - b)

[[1 9 3]
 [4 3 4]
 [0 7 8]]
[[11 15 15]
 [16 13 19]
 [14 15 17]]
[[12 24 18]
 [20 16 23]
 [14 22 25]]
[[-10  -6 -12]
 [-12 -10 -15]
 [-14  -8  -9]]


In [21]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(11,20,(3,3))
print(a)
print(b)
print(np.sum(a + b))
print(np.add(a, b))

[[9 4 7]
 [8 9 9]
 [1 0 4]]
[[12 15 11]
 [16 12 13]
 [16 16 16]]
178
[[21 19 18]
 [24 21 22]
 [17 16 20]]


Array Manipulation

In [22]:
array = np.random.randint(0,10,(2, 3))
print(array)
print(array.shape)

print("TRANSPOSE")

trans = np.transpose(array) # Transpose or array.T
print(trans)
print(trans.shape)

[[4 5 8]
 [1 7 8]]
(2, 3)
TRANSPOSE
[[4 1]
 [5 7]
 [8 8]]
(3, 2)


In [23]:
# Reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

print("RESHAPE")

b = a.reshape(3, 2)
print(b)
print(b.shape)

[[6 1 6]
 [7 3 7]]
(2, 3)
RESHAPE
[[6 1]
 [6 7]
 [3 7]]
(3, 2)
